plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Antonio Pastorino
description: Parole un pò a caso su cose a caso
lang: it
locale: it_IT
url: "http://potential-potato.site"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20